# Generated by Django 5.1.7 on 2026-03-23 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('work_place', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.FileField(upload_to='teachers/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='teachers_te_slug_8a2f80_idx')],
            },
        ),
    ]
